/**
 * @file
 * @brief Offer data structure of `point` in @ref Function or @ref Curve. Offer data structure of `list` consisting of `point`s.
*/
#pragma once
#include<vector>
#include<limits>
#include<iostream>
#include"Exceptions.hpp"
#include<cmath>

using namespace std;

#define DELTA (1e-6)

/**
 * @brief a list of distinct independent variable values.
*/
using IndependentVariableList=vector<double>;

/**
 * @brief a point in function, with independent variable value, function value and some derivative function values.
*/
struct FunctionPoint{
    double x;

    /**
     * @brief The index of vector stands for the order of the highest derivative.
    */
    vector<double> value;

    FunctionPoint(){}

    FunctionPoint(double x,vector<double> value):
    x(x),value(value){}
};

/**
 * @brief a list of @ref FunctionPoint.
 * 
 * Used for @ref Interpolator to interpolate.
*/
using FunctionPointList=vector<FunctionPoint>;

/**
 * @brief a point in curve, with curve value and some tangent vector values.
 * 
 * The index of bigger vector stands for the order of the highest derivative. 
 * While the size of smaller vector is the dimension of curve.
*/
using CurveValue=vector<vector<double>>;

/**
 * @brief a list of @ref CurveValue.
*/
using CurveValueList=vector<CurveValue>;

/**
 * @brief a point in curve, with independent variable value and @ref CurveValue.
*/
struct CurvePoint{
    double t;

    CurveValue value;

    CurvePoint(){}

    CurvePoint(double t,CurveValue value):
    t(t),value(value){}
};

/**
 * @brief a list of @ref CurvePoint with distinct independent variable values.
 * 
 * can be generated by @ref Curve.
*/
using CurvePointList=vector<CurvePoint>;

/**
 * @brief a control point for @ref BezierCurve.
*/
using ControlPoint=CurveValue;

/**
 * @brief list of control points for @ref BezierCurve.
*/
using ControlPointsList=vector<ControlPoint>;

/**
 * @brief for spline to storage @ref ControlPointsList for it's sub-curves.
 */
using ControlPointsList_List=vector<ControlPointsList>;

ControlPoint toControlPoint(const CurvePoint& in);

ControlPointsList toControlPointsList(const CurvePointList& in);

using DifferenceQuotientTable=vector<vector<double> >;

/**
 * @brief definition domain of a function, curve, etc.
 */
struct DefinitionDomain{
    double l///< left endpoint;
    ,r;///< right endpoint;

    DefinitionDomain(double l=numeric_limits<double>::lowest(),double r=numeric_limits<double>::max(),bool lClosed=1,bool rClosed=1)
    {
        set_l(l,lClosed);
        set_r(r,rClosed);
    }

    void set_l(double l,bool lClosed=1){
        this->l=l;
        if(!lClosed) this->l=nextafter(l,numeric_limits<double>::infinity());
    }

    void set_r(double r,bool rClosed=1){
        this->r=r;
        if(!rClosed) this->r=nextafter(r,-numeric_limits<double>::infinity());
    }

    /**
     * @brief merge 2 definition domains.
     */
    static DefinitionDomain merge(const DefinitionDomain& lhs,const DefinitionDomain& rhs);

    /**
     * @brief check if `x` is in the definition domain. 
    */
    bool inDefinitionDomain(double x) const{
        return x>=l && x<=r;
    }

    bool isDefault() const{
        if(this->l==numeric_limits<double>::lowest() && this->r==numeric_limits<double>::max()) return 1;
        return 0;
    }

    IndependentVariableList generateVariableList(int number,bool b_reverse=0) const;
};

ostream& operator<<(ostream& out,const DefinitionDomain& foo);