/**
 * @file
 * @brief Offer data structure of `point` in @ref Function or @ref Curve. Offer data structure of `list` consisting of `point`s.
*/
#pragma once
#include<vector>

using namespace std;

#define EPSILON (1e-15)

/**
 * @brief using in one-sided derivative.
 */
enum class Direction{
    left,
    right,
    DEFAULT
};

/**
 * @brief a list of distinct independent variable values.
*/
typedef vector<double> IndependentVariableList;

/**
 * @brief a point in function, with independent variable value, function value and some derivative function values.
*/
typedef struct FunctionPoint{
    double x;

    /**
     * @brief The index of vector stands for the order of the highest derivative.
    */
    vector<double> value;

    FunctionPoint(){}

    FunctionPoint(double x,vector<double> value):
    x(x),value(value){}
}FunctionPoint;

/**
 * @brief a list of @ref FunctionPoint.
 * 
 * Used for @ref Interpolator to interpolate.
*/
typedef vector<FunctionPoint> FunctionPointList;

/**
 * @brief a point in curve, with curve value and some tangent vector values.
 * 
 * The index of bigger vector stands for the order of the highest derivative. 
 * While the size of smaller vector is the dimension of curve.
*/
typedef vector<vector<double>> CurveValue;

/**
 * @brief a list of @ref CurveValue.
*/
typedef vector<CurveValue> CurveValueList;

/**
 * @brief a point in curve, with independent variable value and @ref CurveValue.
*/
typedef struct CurvePoint{
    double t;

    CurveValue value;

    CurvePoint(){}

    CurvePoint(double t,CurveValue value):
    t(t),value(value){}
}CurvePoint;

/**
 * @brief a list of @ref CurvePoint with distinct independent variable values.
 * 
 * can be generated by @ref Curve.
*/
typedef vector<CurvePoint> CurvePointList;

/**
 * @brief a control point for @ref BezierCurve.
*/
typedef CurveValue ControlPoint;

/**
 * @brief list of control points for @ref BezierCurve.
*/
typedef vector<ControlPoint> ControlPointsList;

/**
 * @brief for spline to storage @ref ControlPointsList for it's sub-curves.
 */
typedef vector<ControlPointsList> ControlPointsList_List;

ControlPoint toControlPoint(const CurvePoint& in);

ControlPointsList toControlPointsList(const CurvePointList& in);