/**
 * @file
 * @brief Offer data structure of `point` in @ref Function or @ref Curve. Offer data structure of `list` consisting of `point`s.
*/
#pragma once
#include<vector>
#include<limits>

using namespace std;

#define EPSILON (1e-15)

/**
 * @brief definition domain of a function, curve, etc.
 */
typedef struct DefinitionDomain{
    double l///< left endpoint;
    ,r;///< right endpoint;
    bool lClosed///< ==1 if left side of the interval is closed.
    ,rClosed;///< ==1 if right side of the interval is closed.

    DefinitionDomain(double l=numeric_limits<double>::lowest(),double r=numeric_limits<double>::max(),bool lClosed=1,bool rClosed=1)
    :l(l),r(r),lClosed(lClosed),rClosed(rClosed){}

    /**
     * @brief merge 2 definition domains.
     */
    static DefinitionDomain merge(const DefinitionDomain& lhs,const DefinitionDomain& rhs);

    /**
     * @brief check if `x` is in the definition domain. 
    */
    bool inDefinitionDomain(double x) const{
        return x>=l && x<=r;
    }

    bool isDefault() const{
        if(this->l==numeric_limits<double>::lowest() && this->r==numeric_limits<double>::max() && this->lClosed==1 && this->rClosed==1) return 1;
        return 0;
    }
    double get_l() const{
        if(lClosed) return l;
        return l+EPSILON;
    }

    double get_r() const{
        if(rClosed) return r;
        return r-EPSILON;
    }
}DefinitionDomain;

/**
 * @brief a list of distinct independent variable values.
*/
typedef vector<double> IndependentVariableList;

/**
 * @brief a point in function, with independent variable value, function value and some derivative function values.
*/
typedef struct FunctionPoint{
    double x;

    /**
     * @brief The index of vector stands for the order of the highest derivative.
    */
    vector<double> value;

    FunctionPoint(){}

    FunctionPoint(double x,vector<double> value):
    x(x),value(value){}
}FunctionPoint;

/**
 * @brief a list of @ref FunctionPoint.
 * 
 * Used for @ref Interpolator to interpolate.
*/
typedef vector<FunctionPoint> FunctionPointList;

/**
 * @brief a point in curve, with curve value and some tangent vector values.
 * 
 * The index of bigger vector stands for the order of the highest derivative. 
 * While the size of smaller vector is the dimension of curve.
*/
typedef vector<vector<double>> CurveValue;

/**
 * @brief a list of @ref CurveValue.
*/
typedef vector<CurveValue> CurveValueList;

/**
 * @brief a point in curve, with independent variable value and @ref CurveValue.
*/
typedef struct CurvePoint{
    double t;

    CurveValue value;

    CurvePoint(){}

    CurvePoint(double t,CurveValue value):
    t(t),value(value){}
}CurvePoint;

/**
 * @brief a list of @ref CurvePoint with distinct independent variable values.
 * 
 * can be generated by @ref Curve.
*/
typedef vector<CurvePoint> CurvePointList;

/**
 * @brief a control point for @ref BezierCurve.
*/
typedef CurveValue ControlPoint;

/**
 * @brief list of control points for @ref BezierCurve.
*/
typedef vector<ControlPoint> ControlPointsList;

/**
 * @brief for spline to storage @ref ControlPointsList for it's sub-curves.
 */
typedef vector<ControlPointsList> ControlPointsList_List;

ControlPoint toControlPoint(const CurvePoint& in);

ControlPointsList toControlPointsList(const CurvePointList& in);