#include"../lib/Interpolator_NewtonFormula.hpp"
#include"../lib/Function.hpp"
#include<iostream>
#include<vector>

using namespace std;

class F:public Function{
public:
    double operator()(double x) const override{
        return 1/(1+x*x);
    }
};

int main(){
    vector<double> interpolatingPoints[4];
    for(int n=2;n<=8;n+=2){
        for(int i=0;i<=n;i++){
            interpolatingPoints[(n-2)/2].push_back(-5+10.0*i/n);
        }
    }

    F f;
    Interpolator_N Interpolator_N{f};
    for(int i=0;i<4;i++){
        Interpolator_N.setInterpolatingPoints(interpolatingPoints[i]);
        cout<< "Polynomial generated by "<<2+i*2<<" interpolating points:"<<endl;
        Interpolator_N.interpolate().print();
        cout<<endl;
    }
    return 0;
}