#include"../lib/Interpolator_NewtonFormula.hpp"
#include"../lib/Function.hpp"
#include<iostream>
#include<vector>

using namespace std;

/// @cond
class F:public Function{
    using Function::Function;
    double getValue(double x) const override{
        return 1/(1+x*x);
    }
};
/// @endcond

int main(){
    F f(-5,5);

    FunctionPointList list[4];
    double foo[4]={2,4,6,8};
    for(int it=0;it<=3;it++){
        int n=foo[it];
        list[it]=f.generatePointList(n+1,0);
    }
    
    Interpolator_N interpolator_N;
    for(int i=0;i<4;i++){
        interpolator_N.setInterpolationPoints(list[i]);
        cout<< "Polynomial generated by "<<foo[i]<<" interpolation points:"<<endl;
        interpolator_N.interpolate().print();
        cout<<endl;
    }
    return 0;
}