#include"../lib/Interpolator_NewtonFormula.hpp"
#include"../lib/Function.hpp"
#include"../lib/LatexOutputer.hpp"
#include"../lib/Polynomial.hpp"
#include<iostream>
#include<vector>

using namespace std;

/// @cond
class F:public Function{
    using Function::Function;
    double getValue(double x) const override{
        return 1/(1+x*x);
    }
};
/// @endcond

int main(){
    F f(DefinitionDomain{-5,5});

    FunctionPointList list[4];
    int foo[4]={2,4,6,8};
    for(int it=0;it<=3;it++){
        int n=foo[it];
        list[it]=f.generatePointList(n+1,0);
    }
    
    Interpolator_N interpolator_N;
    LatexOutputer outputer("B.tex");
    outputer.quickStart("Image of Question B",-5,5);
    outputer.addLine("{1/(1+x*x)}","exact function","dashed");
    for(int i=0;i<4;i++){
        interpolator_N.setInterpolationPoints(list[i]);
        cout<< "Polynomial generated by "<<foo[i]<<" interpolation points:"<<endl;
        Polynomial bar=interpolator_N.interpolate();
        bar.print();
        cout<<endl;
        string legendentry="$p_{n="+to_string(foo[i])+"}(x)$";
        outputer.addLine(bar.getLatexFormatString(),legendentry);
    }
    outputer.quickEnd();
    return 0;
}