#include"../lib/Function.hpp"
#include"../lib/Interpolator_NewtonFormula.hpp"
#include<vector>
#include<cmath>

using namespace std;

const double PI=acos(-1.);

/**
 * @brief The function of Question C.
*/
class F_C:public Function{
    double operator()(double x) const override{
        return 1/(1+25*x*x);
    }
};

int main(){
    vector<double> interpolatingPoints[4];
    for(int i=0;i<4;i++){
        int n=(i+1)*5;
        for(int j=1;j<=n;j++){
            interpolatingPoints[i].push_back(cos((2*j-1)*PI/(2*n)));
        }
    }
    F_C f;
    Interpolator_N Interpolator_N{f};
    for(int i=0;i<4;i++){
        Interpolator_N.setInterpolatingPoints(interpolatingPoints[i]);
        cout<< "Polynomial generated by "<<5+i*5<<" interpolating points:"<<endl;
        Interpolator_N.interpolate().print();
        cout<<endl;
    }
    return 0;
}