#include"../lib/Function.hpp"
#include"../lib/Interpolator_NewtonFormula.hpp"
#include"../lib/LatexOutputer.hpp"
#include<vector>
#include<cmath>
#include<iostream>

using namespace std;

const double PI=acos(-1.);

/// @cond
class F:public Function{
    using Function::Function;
    double getValue(double x) const override{
        return 1/(1+25*x*x);
    }
};
/// @endcond

int main(){
    F f(DefinitionDomain{-1,1});

    IndependentVariableList vlist[4];
    FunctionPointList plist[4];
    int foo[4]={5,10,15,20};
    for(int i=0;i<4;i++){
        int n=foo[i];
        for(int j=1;j<=n;j++){
            vlist[i].push_back(cos((2*j-1)*PI/(2*n)));
        }
        plist[i]=f.generatePointList(vlist[i],0);
    }
    
    Interpolator_N interpolator_N;
    LatexOutputer outputer("C.tex");
    outputer.quickStart(0,"Image of Question C",DefinitionDomain{-1,1});
    outputer.addLine("{1/(1+25*x*x)}","exact function","dashed");
    for(int i=0;i<4;i++){
        interpolator_N.setInterpolationPoints(plist[i]);
        Polynomial bar=interpolator_N.interpolate();
        cout<< "Polynomial generated by "<<foo[i]<<" interpolation points:"<<endl<<bar<<endl<<endl;
        outputer.addLine(bar.getLatexFormatString(),"$p_{n="+to_string(foo[i])+"}(x)$");
    }
    outputer.quickEnd();
    return 0;
}